// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'dart:typed_data' as i2;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [dioCache];
  late final Shape0 dioCache = Shape0(
    source: i0.VersionedTable(
      entityName: 'DioCache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get cacheKey =>
      columnsByName['cacheKey']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get cacheControl =>
      columnsByName['cacheControl']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get content =>
      columnsByName['content']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get eTag =>
      columnsByName['eTag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get expires =>
      columnsByName['expires']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get headers =>
      columnsByName['headers']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get lastModified =>
      columnsByName['lastModified']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get maxStale =>
      columnsByName['maxStale']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get requestDate =>
      columnsByName['requestDate']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get responseDate =>
      columnsByName['responseDate']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cacheKey',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'date',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cacheControl',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<i2.Uint8List> _column_3(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'content',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'eTag',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expires',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<i2.Uint8List> _column_6(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'headers',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'lastModified',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'maxStale',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'priority',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'requestDate',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'responseDate',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [dioCache];
  late final Shape1 dioCache = Shape1(
    source: i0.VersionedTable(
      entityName: 'DioCache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get cacheKey =>
      columnsByName['cacheKey']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get cacheControl =>
      columnsByName['cacheControl']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get content =>
      columnsByName['content']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get eTag =>
      columnsByName['eTag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get expires =>
      columnsByName['expires']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get headers =>
      columnsByName['headers']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get lastModified =>
      columnsByName['lastModified']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get maxStale =>
      columnsByName['maxStale']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get requestDate =>
      columnsByName['requestDate']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get responseDate =>
      columnsByName['responseDate']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get statusCode =>
      columnsByName['statusCode']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'statusCode',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
