name: Dart

on:
  push:
    branches: 
      - master
      - gha
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Prepare
      - uses: actions/checkout@v7
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Activate melos
        run: |
          dart pub global activate melos

      - name: Install dependencies
        run: melos bs

      # Verify
      - name: Verify formatting
        run: melos format

      - name: Analyze project source
        run: melos analyze

      # Test
      - name: Test ObjectBox
        working-directory: http_cache_objectbox_store
        run: |
          bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)
      
      - name: Run all tests
        run: |
          dart pub global activate full_cover
          full_cover
      
      # Coverage
      - name: Upload global coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          disable_search: true
          files: coverage/lcov.info
